trigger:
  batch: 'true'
  branches:
    include:
    - 'development-4.4x'

variables:
  githubToken: $(GITHUB_READONLY) 
- group: 'Pipeline Agent Pool Names'


pool:
  name: $(BuildPool.AzureManaged)
  demands:
  - 'ImageOverride -equals ubuntu-latest'

# resources:
#   repositories:
#     - repository: modules-dotnet
#       type: github
#       name: IntentArchitect/Intent.Modules.NET
#       ref: refs/heads/$(Build.SourceBranchName)  # Using the same branch name as the pipeline's branch

steps:

  - checkout: self
    persistCredentials: 'true'
    fetchDepth: '1'

  - script: |
    git clone https://$(GitHubToken)@github.com/jp-seini/Intent.Modules.NET.git
  displayName: 'Clone GitHub Repository using PAT'

  #- checkout: modules-dotnet  # Checkout the branch from the second repo  

