trigger:
  batch: 'true'
  branches:
    include:
    - 'development-4.4x'

resources:
  pipelines:
  - pipeline: 'ModulesDotNetPipeline'
    source: 'IntentSoftware.Intent.Modules.NET'
    trigger: true
  - pipeline: 'ModulesCommonPipeline'
    source: 'IntentSoftware.Intent.Modules'
    trigger: true

parameters:
- name: modules
  type: object
  default:
    - repositoryName: modules-dotnet
      repositoryUrl: https://github.com/IntentArchitect/Intent.Modules.NET.git
      folderName: Intent.Modules.NET
      destinationFolder: modules-dotnet
    - repositoryName: 'modules-common'
      repositoryUrl: "https://github.com/IntentArchitect/Intent.Modules.git"
      folderName: Intent.Modules
      destinationFolder: modules-common

variables:
  - group: 'Pipeline Agent Pool Names'

pool:
  name: $(BuildPool.AzureManaged)
  demands:
  - 'ImageOverride -equals ubuntu-latest'

steps:

  # checkout the branch docs repo
  - checkout: self
    persistCredentials: 'true'
    fetchDepth: '1'
    displayName: 'Checkout Docs branch'

  # calculate the repo and branch which triggered this pipeline
  - script: |
      # Check which pipeline triggered the pipeline and set a variable accordingly
      if [ "$(resources.pipeline.ModulesDotNetPipeline.sourceBranch)" != "" ]; then
        echo "##vso[task.setvariable variable=triggeredByPipeline]IntentSoftware.Intent.Modules.NET"
        echo "##vso[task.setvariable variable=triggeredByBranch]$(resources.pipeline.ModulesDotNetPipeline.sourceBranch)"
      elif [ "$(resources.pipeline.ModulesCommonPipeline.sourceBranch)" != "" ]; then
        echo "##vso[task.setvariable variable=triggeredByPipeline]IntentSoftware.Intent.Modules"
        echo "##vso[task.setvariable variable=triggeredByBranch]$(resources.pipeline.ModulesCommonPipeline.sourceBranch)"
      else
        echo "##vso[task.setvariable variable=triggeredByPipeline]IntentSoftware.Docs"
        echo "##vso[task.setvariable variable=triggeredByBranch]$(Build.SourceBranchName)"
      fi
    displayName: 'Determine and Set Variables for Triggered Pipeline'

  - pwsh: |
      Write-Host "Triggered By Pipeline: $(triggeredByPipeline)"
      Write-Host "Triggered By Branch: $(triggeredByBranch)"
    displayName: 'Output pipeline variables'
  
  # first clean just to make sure all fresh incase
  - pwsh: |
      git clean -fdx
    displayName: '$git clean'

    # for each of the above configured modules (under parameters)
  - ${{ each module in parameters.modules }} :
    - task: PowerShell@2
      displayName: "${{ module.repositoryName }} Module Merge"
      inputs:
        targetType: 'inline'
        pwsh: true
        script: ./PipelineScripts/merge-repo-docs.ps1 "$(triggeredByBranch)" "${{ module.repositoryUrl }}" "${{ module.folderName }}" "${{ module.destinationFolder }}" 1

  - pwsh: |
      dotnet tool install docfx
    displayName: 'dotnet tool install docfx'

  - pwsh: |
      dotnet docfx $(Build.SourcesDirectory)/docfx.json
    displayName: 'run docfx'

  - pwsh: |
      az storage blob sync -s '$(Build.SourcesDirectory)/_site' -d '($(triggeredByBranch) -split '/')[-1]/' --container '$(intentarchitect.storageContainer)' --account-name '$(intentarchitect.preprod.storageAccountName)' --account-key '$(intentarchitect.preprod.storageAccountKey)' --delete-destination 'true'
    displayName: 'Pre-production storage sync'
    condition: and(succeeded(), ne(variables['triggeredByBranch'], 'master'), ne(variables['triggeredByBranch'], 'refs/heads/master'))

  # - pwsh: |
  #     az storage blob sync -s '$(Build.SourcesDirectory)/_site' --container '$(intentarchitect.storageContainer)' --account-name '$(intentarchitect.storageAccountName)' --account-key '$(intentarchitect.storageAccountKey)' --delete-destination 'true'
  #   displayName: 'Production storage sync'
  #   condition: and(succeeded(), or( eq(variables['triggeredByBranch'], 'master'), eq(variables['triggeredByBranch'], 'refs/heads/master') )


