trigger:
  batch: 'true'
  branches:
    include:
    - 'development-4.4x'

parameters:
- name: modules
  type: object
  default:
    - repositoryName: 'modules-dotnet'
      repositoryUrl: $(DOTNET_REPO_URL) # this has to be set in the variables section due to the way in which variables are resolved

variables:
  - group: 'Pipeline Agent Pool Names'
  - name : DOTNET_REPO_URL
    value: "https://$env:GITHUB_READONLY@github.com/IntentArchitect/Intent.Modules.NET.git"

pool:
  name: $(BuildPool.AzureManaged)
  demands:
  - 'ImageOverride -equals ubuntu-latest'

# resources:
#   repositories:
#     - repository: modules-dotnet
#       type: github
#       name: IntentArchitect/Intent.Modules.NET
#       ref: refs/heads/$(Build.SourceBranchName)  # Using the same branch name as the pipeline's branch
#       token: $(GITHUB_READONLY)  

steps:

  - checkout: self
    persistCredentials: 'true'
    fetchDepth: '1'

  - pwsh: |
      ls

  - ${{ each module in parameters.modules }} :
      - pwsh: |
          echo ${{ module.repositoryUrl }}
        env:
          GITHUB_READONLY: $(GITHUB_READONLY)

      - pwsh: |
          $GitUrl = ${{ module.repositoryUrl }}
          git clone $GitUrl 
        env:
          GITHUB_READONLY: $(GITHUB_READONLY)

  - pwsh: |
      ls
    
  # - checkout: modules-dotnet  # Checkout the branch from the second repo  

